project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://ppiatkow55.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    right:
      - text: "Mini Project 01"
        href: "./Mp1.html"
      - text: "Mini Project 02
        href: "./mp2.html"
      - text: "MP3" 
      - text: "MP4"
    
format:
  html:
    theme: cerulean
    toc: false
    
    

editor:
  mode: source